name: BUILD

on: push

env:
  AWS_REGISTRY: 339570402237.dkr.ecr.eu-west-1.amazonaws.com
  AWS_SERVER_REPOSITORY: company/orbis/django
  AWS_CLIENT_REPOSITORY: company/orbis/client

jobs:
  client-tests:
    name: Client-side Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: frontend-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            frontend-build-
      - name: yarn install, and test
        env:
          CI: "true"
          GITHUB_REGISTRY_TOKEN: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
        working-directory: client
        run: |
          yarn install
          yarn test:ci
      - name: Upload Frontend Test Results
        uses: actions/upload-artifact@v1
        with:
          name: Frontend Test Report
          path: client/jest_html_reporters.html

  server-tests:
    name: Server-side Tests
    runs-on: ubuntu-latest
    container:
      image: python:3.6.8
      ports:
        - "8000:8000"
      env:
        SYS_ENV: ci
        DJANGO_SETTINGS_MODULE: core.settings
        DJANGO_DB_HOST: 127.0.0.1:5666
    services:
      db:
        image: kartoza/postgis:11.0-2.5
        env:
          POSTGRES_DBNAME: orbis
          POSTGRES_USER: orbis
          POSTGRES_PASS: orbis
          ALLOW_IP_RANGE: 0.0.0.0/0
        ports:
          - "5666:5432"
    steps:
      - uses: actions/checkout@v1
      - name: Setup container
        run: |
          apt-get update && apt-get install -y postgresql-client python3-gdal
          pip3 install --upgrade pip
          pip3 install --upgrade pipenv

      - name: Install Dependencies and Run Tests
        working-directory: server
        run: |
          pipenv install --dev
          pipenv run ./manage.py migrate --noinput
          pipenv run pytest --html=backend-report.html --self-contained-html ./
      - name: Upload Backend Test Results
        uses: actions/upload-artifact@v1
        with:
          name: Backend Test Report
          path: server/backend-report.html

  build-client-docker:
    needs: [client-tests]
    name: Build, Tag and Push Client Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dependencies
        run: ./scripts/ci-setup-deps.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker Image
        run: |
          export GIT_SHA=${GITHUB_SHA:0:7}
          DOCKER_BUILDKIT=1 docker build . -t ${AWS_REGISTRY}/${AWS_CLIENT_REPOSITORY}:${GIT_SHA} --build-arg COMMIT_SHA=${GIT_SHA} --build-arg TOKEN=${{ secrets.GITHUB_REGISTRY_TOKEN }} -f ./Dockerfile.client.deployment

      - name: Push image to AWS Docker Registry
        run: |
          export GIT_SHA=${GITHUB_SHA:0:7}
          docker push ${AWS_REGISTRY}/${AWS_CLIENT_REPOSITORY}:${GIT_SHA}

  build-server-docker:
    needs: [server-tests]
    name: Build, Tag and Push Server Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dependencies
        run: ./scripts/ci-setup-deps.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker Image
        run: |
          export GIT_SHA=${GITHUB_SHA:0:7}
          DOCKER_BUILDKIT=1 docker build . -t ${AWS_REGISTRY}/${AWS_SERVER_REPOSITORY}:${GIT_SHA} --build-arg COMMIT_SHA=${GIT_SHA} --build-arg TOKEN=${{ secrets.GITHUB_REGISTRY_TOKEN }} -f ./Dockerfile.server.deployment

      - name: Push image to AWS Docker Registry
        run: |
          export GIT_SHA=${GITHUB_SHA:0:7}
          docker push ${AWS_REGISTRY}/${AWS_SERVER_REPOSITORY}:${GIT_SHA}

  deploy-to-testing:
    needs: [build-client-docker, build-server-docker]
    name: Deploy to Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dependencies
        run: ./scripts/ci-setup-deps.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Deployment
        run: |
          set -eu

          # Used to query for PRs associated with the commit
          export GITHUB_TOKEN="${{ github.token }}"

          # Required for createDeployment.js to use the AWS profiles defined by ci-setup-deps.sh
          export AWS_SDK_LOAD_CONFIG=1

          set -x

          cd scripts/create-deployment
          yarn install

          REPO_OWNER="$(dirname "$GITHUB_REPOSITORY")"
          REPO_NAME="$(basename "$GITHUB_REPOSITORY")"

          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            node createDeployment.js \
              --environment testing \
              --repo-owner "$REPO_OWNER" \
              --repo-name "$REPO_NAME" \
              deploy-primary \
              --commit "$GITHUB_SHA"

          else
            node createDeployment.js \
              --environment testing \
              --repo-owner "$REPO_OWNER" \
              --repo-name "$REPO_NAME" \
              deploy-associated-prs \
              --commit "$GITHUB_SHA"
          fi
